AddressBook/Models/ErrorViewModel.cs
namespace AddressBook.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AddressBook/Models/LOC_CountryModel.cs
namespace AddressBook.Models
{
    public class LOC_CountryModel
    {
        public int? COUNTRYID  { get; set; }
        public string COUNTRYNAME { get; set; }
        = string.Empty;
        public string COUNTRYCODE { get; set; }
        = string.Empty;
        public DateTime CREATED { get; set; }
        public DateTime MODIFIED{ get; set; }


    }
}

AddressBook/Models/LOC_StateModel.cs
namespace AddressBook.Models
{
    public class LOC_StateModel
    {
        public int STATEID { get; set; }
        public string STATENAME { get; set; }
        public string COUNTRYNAME { get; set; }
        public DateTime CREATED { get; set; }
        public DateTime MODIFIED { get; set; }
    }
}

AddressBook/Controllers/HomeController.cs
using AddressBook.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AddressBook.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AddressBook/Controllers/LOC_CountryController.cs
using AddressBook.Models;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;
using System.Data;
using System.Data.SqlClient;
using System.Reflection;

namespace AddressBook.Controllers
{
    public class LOC_CountryController : Controller
    { 
        private IConfiguration Configuration;
        public LOC_CountryController(IConfiguration _configuration)
        {
            Configuration = _configuration;  
        }
        public IActionResult Index()
        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "SELECTALLOC_Country";
            DataTable dt = new DataTable();
            SqlDataReader sdr = cmd.ExecuteReader();
            dt.Load(sdr); 
            

            return View("LOC_CountryList",dt);
        }
        public IActionResult Delete(int COUNTRYID)
        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand(); 
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "DELETELOC_Country";
            cmd.Parameters.AddWithValue("@COUNTRYID", COUNTRYID);
            cmd.ExecuteNonQuery();
            conn.Close();
            return RedirectToAction("Index");


        }
        public IActionResult Add(int? COUNTRYID)

        {
            if (COUNTRYID != null)
            {
                string str = this.Configuration.GetConnectionString("myConnectionString");
                SqlConnection conn = new SqlConnection(str);
                conn.Open();
                SqlCommand cmd = conn.CreateCommand();
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandText = "SelectByPKLOC_Country";
                cmd.Parameters.AddWithValue("@COUNTRYID",COUNTRYID);
                DataTable dt = new DataTable();
                SqlDataReader sdr = cmd.ExecuteReader();
                dt.Load(sdr);
                LOC_CountryModel modelLOC_Country = new LOC_CountryModel();
                foreach (DataRow dr in dt.Rows)
                {
               
                    modelLOC_Country.COUNTRYCODE = dr["COUNTRYCODE"].ToString();
                    modelLOC_Country.COUNTRYNAME = dr["COUNTRYNAME"].ToString();
                    //modelLOC_Country.CREATED = Convert.ToDateTime(dr["CREATED"]);
                    //modelLOC_Country.MODIFIED = Convert.ToDateTime(dr["MODIFIED"]);
                }
                return View("LOC_CountryAddEdit", modelLOC_Country);
            }
            return View("LOC_CountryAddEdit");
        }
        [HttpPost]
        public IActionResult Save(LOC_CountryModel modelLOC_Country)
        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            if(modelLOC_Country.COUNTRYID == null)
            {
                cmd.CommandText = "InsertLOC_Country";
               
            }
            else
            {
                cmd.CommandText = "UPDATELOC_Country";
                cmd.Parameters.AddWithValue("@COUNTRYID", modelLOC_Country.COUNTRYID);
            }
            cmd.Parameters.AddWithValue("@COUNTRYNAME", modelLOC_Country.COUNTRYNAME);
            cmd.Parameters.AddWithValue("@COUNTRYCODE", modelLOC_Country.COUNTRYCODE);
           // cmd.Parameters.AddWithValue("@MODIFIED", DateTimeOffset.Now);

            cmd.ExecuteNonQuery();
            
            conn.Close();

            return RedirectToAction("Index");
        }
       
    }
}

AddressBook/Controllers/LOC_StateController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;

namespace AddressBook.Controllers
{
    public class LOC_StateController : Controller
    {
        private IConfiguration Configuration;
        public LOC_StateController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        

        public IActionResult Index()
        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "SELECTALLOC_State";
            DataTable dt = new DataTable();
            SqlDataReader sdr = cmd.ExecuteReader();
            dt.Load(sdr);
            return View("LOC_StateList",dt);
        }
        public IActionResult Delete(int ID)
        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "DELETELOC_State";
            cmd.Parameters.AddWithValue("@ID", ID);
           cmd.ExecuteNonQuery();
            conn.Close();
            return RedirectToAction("Index");
        }
    }
}

AddressBook/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AddressBook/Views/LOC_Country/LOC_CountryAddEdit.cshtml
@model LOC_CountryModel
<div class="row"> 
    <div class="col-md-12">
        <form method="post" asp-controller="LOC_Country" asp-action="Save">
            @Html.HiddenFor(x=>x.COUNTRYID)
            <div class="form-group">
                <label>CountryName</label>
                <input type="text" class="form-control" asp-for="COUNTRYNAME" placeholder="Enter name" />
            </div>
            <div class="form-group">
                <label>CountryCode</label>
                <input type="text" class="form-control" asp-for="COUNTRYCODE" placeholder="Enter code" />
            </div>
           @* <div class="form-group">
                <label>Created</label>
                <input type="date" class="form-control" asp-for="CREATED" placeholder="Enter create date" />
            </div>
          
            <div class="form-group">
                <label>Modified</label>
                <input type="date" class="form-control" asp-for="MODIFIED" placeholder="Enter modified date" />
            </div>*@
            <hr />
            <input type="submit" value="Save"/>
          

        </form>
    </div>
</div>

AddressBook/Views/LOC_Country/LOC_CountryList.cshtml
@{
    //ViewData["Title"] = "LOC_CountryList";
   // Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Data;
@model DataTable;
<div class="container">
    <a class="btn btn-success" asp-controller="LOC_Country" asp-action="Add">Add Country</a>
    <br />
<table class="table table-responsive table-sm">
    <thead>
        <tr>
            <th>CountryID</th>
            <th>CountryName</th>
            <th>Created</th>
            <th>Modified</th>
        </tr>
    </thead>
    <tbody>
        @foreach (DataRow d in Model.Rows)
        {
            <tr>
                <td>@d["COUNTRYID"]</td>
                <td>@d["COUNTRYNAME"]</td>
                <td>@Convert.ToDateTime(d["CREATED"]).ToString("dd-MM-yyyy")</td>
                <td>@Convert.ToDateTime(d["MODIFIED"]).ToString("dd-MM-yyyy")</td>
                <td>
                        <form method="post" asp-controller="LOC_Country" asp-action="Delete">
        <input type="hidden" name="COUNTRYID" value="@Convert.ToInt32(d["COUNTRYID"])">
        <button type="submit" class="btn btn-danger btn-xs"
        onclick="return fun1();">Delete</button></form></td>
            </tr>
        }
    </tbody>

</table>
</div>
@section Scripts
{
    <script>
               function fun1(){
                   if(confirm("Are you sure you want to delete?"))
                   return true;
                   else{
                       return false;
                   }

               }
    </script>
}

AddressBook/Views/LOC_State/LOC_StateList.cshtml
@using System.Data
@model DataTable;

<table class="table table-responsive table-sm">
    <thead>
        <tr>
            <th>StateID</th>
            <th>StateName</th>
            <th>CountryName</th>
            <th>Created</th>
            <th>Modified</th>
        </tr>
    </thead>
    <tbody>
        @foreach (DataRow d in Model.Rows)
        {
            <tr>
                <td>@d["STATEID"]</td>
                <td>@d["STATENAME"]</td>
                <td>@d["COUNTRYNAME"]</td>
                <td>@Convert.ToDateTime(d["CREATED"]).ToString("dd-MM-yyyy")</td>
                <td>@Convert.ToDateTime(d["MODIFIED"]).ToString("dd-MM-yyyy")</td>
                <td>
                    <form method="post" asp-controller="LOC_State" asp-action="Delete">
                        <input type="hidden" name="ID" value="@Convert.ToInt32(d["STATEID"])">
                        <button type="submit" class="btn btn-danger btn-xs"
                                onclick="return fun1();">
                            Delete
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

</table>
@section Scripts
{
<script>
    function func1(){
        if(confirm("Are you sure you want to delete?"))
        return true;
        else{
            return false;
        }
    }
</script>
}

AddressBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AddressBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AddressBook.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="LOC_Country" asp-action="Index">Country</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LOC_State" asp-action="Index">State</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AddressBook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>